---

 - hosts: all
   become: yes
   tasks:
   pre_tasks:

    - name: updating repo cache ( local and amazon linux )
      tags: always
      dnf: 
       update_cache: yes
      changed_when: false
      when: ansible_distribution in [[ "Amazon","RedHat" ]] 

    - name: updating repo cache ( ubuntu )
      tags: always
      apt:
       update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu" 

 - hosts: all
   become: yes
   roles:
    - base

 - hosts: workstations
   become: yes
   roles:
    - workstations 

 - hosts: web_servers
   become: yes
   roles:
    - web_servers
 
 - hosts: db_servers      
   become: yes
   roles:
    - db_servers 

...
