---

 - hosts: all
   become: yes
   tasks:
   pre_tasks:

    - name: install updates ( local and amazon linux )
      dnf: 
       update_only: yes
       update_cache: yes
      when: ansible_distribution in [[ "Amazon","RedHat" ]] 

    - name: install updates ( ubuntu )
      apt:
       upgrade: dist
       update_cache: yes
      when: ansible_distribution == "Ubuntu" 


 - hosts: web_servers
   become: true
   tasks:

    - name: installing httpd and php packages for amazon linux servers
      dnf:
       name: 
          - httpd
          - php
       state: latest
      when: ansible_distribution == "Amazon"

    - name: installing apache and php packages for Ubuntu servers
      apt:
        name: 
          - apache2
          - libapache2-mod-php  
        state: latest
      when: ansible_distribution == "Ubuntu"

...
