---

 - hosts: all
   become: yes
   tasks:
   pre_tasks:

    - name: install updates ( local and amazon linux )
      tags: always
      dnf: 
       update_only: yes
       update_cache: yes
      when: ansible_distribution in [[ "Amazon","RedHat" ]] 

    - name: install updates ( ubuntu )
      tags: always
      apt:
       upgrade: dist
       update_cache: yes
      when: ansible_distribution == "Ubuntu" 


 - hosts: web_servers
   become: true
   tasks:

    - name: installing httpd and php packages for amazon linux servers
      tags: http,httpd,php,amazon
      dnf:
       name: 
          - httpd
          - php
       state: latest
      when: ansible_distribution == "Amazon"

    - name: installing apache and php packages for Ubuntu servers
      tags: apache,apache2,ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php  
        state: latest
      when: ansible_distribution == "Ubuntu"


 - hosts: db_servers      
   become: yes
   tasks: 

    - name: install mariadb package (Rhel9)
      tags: db,mariadb,redhat
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "RedHat"

...
