- name: installing apache and php packages
  tags: http,httpd,php,amazon,apache
  package:   
    name:
     - "{{ apache_package_name }}"
     - "{{ php_package_name }}"
    state: latest
  
- name: start and enable apache service
  tags: service,enabled,http,httpd,redhat,amazon
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change email address for admin
  tags: http,httpd,amazon
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Amazon"
  notify: restart_apache

- name: installing apache and php packages for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: copy default html file for site
  tags: apache,apache2,http,httpd,copy
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644


