- name: adding ssh key for william
  authorized_key: 
    user: william
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJTIb4nrSwNU/vM12cKBvheHa1eDxFLxi6MLo5OAtSP/ ansible key"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
